# Generated by Django 6.0.6 on 2026-06-08 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics_mgmt', '0001_initial'),
        ('core', '0001_initial'),
        ('student_mgmt', '0001_initial'),
        ('teacher_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_mgmt.teacher'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mgmt.class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mgmt.class'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_mgmt.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_mgmt.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='student_mgmt.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_mgmt.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_mgmt.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_name', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_name', 'day', 'period_number')},
        ),
    ]
