# Generated by Django 6.0.6 on 2026-06-08 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics_mgmt', '0002_initial'),
        ('core', '0001_initial'),
        ('exam_mgmt', '0001_initial'),
        ('student_mgmt', '0001_initial'),
        ('teacher_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mgmt.class'),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_mgmt.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_mgmt.subject'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_mgmt.teacher'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam_mgmt.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student_mgmt.student'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_mgmt.examtype'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_mgmt.examtype'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='student_mgmt.student'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'exam_type', 'academic_year')},
        ),
    ]
