# Generated by Django 6.0.6 on 2026-06-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repaid', 'Fully Repaid')], default='pending', max_length=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='teacher_mgmt.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, help_text='House Rent Allowance', max_digits=8)),
                ('da', models.DecimalField(decimal_places=2, default=0, help_text='Dearness Allowance', max_digits=8)),
                ('ta', models.DecimalField(decimal_places=2, default=0, help_text='Travel Allowance', max_digits=8)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund', max_digits=8)),
                ('esi_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='teacher_mgmt.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('working_days', models.IntegerField(default=26)),
                ('present_days', models.IntegerField(default=26)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='bank', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('hold', 'On Hold')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='teacher_mgmt.teacher')),
                ('salary_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_mgmt.salarystructure')),
            ],
            options={
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
