# Generated by Django 6.0.6 on 2026-06-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_number', models.CharField(max_length=20, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('stops', models.TextField(help_text='Comma separated stop names')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('conductor_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('capacity', models.IntegerField(default=40)),
                ('morning_departure', models.TimeField()),
                ('evening_departure', models.TimeField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_stop', models.CharField(max_length=100)),
                ('drop_stop', models.CharField(max_length=100)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='transport_mgmt.busroute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='student_mgmt.student')),
            ],
        ),
    ]
