# Generated by Django 6.0.6 on 2026-06-08 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fees_mgmt', '0001_initial'),
        ('student_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='student_mgmt.student'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='student_mgmt.class'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees_mgmt.feestructure'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='student_mgmt.student'),
        ),
    ]
