# Generated by Django 6.0.6 on 2026-06-08 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication_mgmt', '0001_initial'),
        ('student_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_mgmt.class'),
        ),
    ]
